#!/bin/sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$SCRIPT_DIR/cfgs"
cat << EOF > "$SCRIPT_DIR/cfgs/configFile"
Host host1
    HostName $1
    User $2
    PubkeyAcceptedKeyTypes +ssh-rsa,ssh-ed25519,ecdsa-sha2-nistp256,rsa-sha2-256,rsa-sha2-512
    HostKeyAlgorithms +ssh-rsa,ssh-ed25519,ecdsa-sha2-nistp256,rsa-sha2-256,rsa-sha2-512
EOF

chmod 600 "$SCRIPT_DIR/cfgs/configFile"
